# Generated by Django 3.2.1 on 2021-05-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_list',
            name='date',
            field=models.DateTimeField(auto_created=True, default='2021-05-06 12:00'),
            preserve_default=False,
        ),
    ]
