# Generated by Django 3.2.1 on 2021-05-06 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_todo_list_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo_list',
            old_name='date',
            new_name='datetime',
        ),
    ]
