# Generated by Django 3.2.1 on 2021-05-06 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_email_create_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='title',
            new_name='subject',
        ),
    ]
